apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-deployment
  labels:
    app: currency-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-service
  template:
    metadata:
      labels:
        app: currency-service
    spec:
      containers:
      - name: currency-service
        image: docker.io/yugandhar7/currency-svc:v3
        ports:
        - containerPort: 7000
        env:
        - name: DISABLE_PROFILER
          value: "true"
        - name: PORT
          value: "7000"
        envFrom:
          - configMapRef:
              name: app-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 7000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 7000
          initialDelaySeconds: 15
          periodSeconds: 5