apiVersion: v1
kind: Service
metadata:
  name: currency-service
  labels:
    app: currency-service
spec:
  type: ClusterIP
  selector:
    app: currency-service
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      