apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
  labels:
    app: product-catalog-service
spec:
  type: ClusterIP
  selector:
    app: product-catalog-service
  ports:
    - protocol: TCP
      port: 3550
      targetPort: 3550