apiVersion: v1
kind: Service
metadata:
  name: ad-service
  labels:
    app: ad-service 
spec:
  type: ClusterIP
  selector:
    app: ad-service
  ports:
    - protocol: TCP
      port: 9555
      targetPort: 9555
      