apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-deployment
  labels:
    app: ad-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad-service
  template:
    metadata:
      labels:
        app: ad-service
    spec:
      containers:
      - name: ad-service
        image: docker.io/yugandhar7/adservice:v2
        ports:
        - containerPort: 9555   
        envFrom:
          - configMapRef:
              name: app-config  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 9555
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9555
          initialDelaySeconds: 15
          periodSeconds: 5

            
            