apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:

  # =========================
  # GLOBAL
  # =========================
  ENVIRONMENT: "dev"
  LOG_LEVEL: "info"

  # =========================
  # FRONTEND
  # =========================
  FRONTEND_PORT: "8080"

  # =========================
  # CORE SERVICES
  # =========================
  CART_SERVICE_URL: "http://cartservice:7070"
  PRODUCT_CATALOG_SERVICE_URL: "http://productcatalogservice:3550"
  RECOMMENDATION_SERVICE_URL: "http://recommendationservice:8080"
  AD_SERVICE_URL: "http://ad-service:9555"
  EMAIL_SERVICE_URL: "http://email-service:8080"

  # =========================
  # PAYMENT & SHIPPING
  # =========================
  PAYMENT_SERVICE_URL: "http://paymentservice:50051"
  SHIPPING_SERVICE_URL: "http://shippingservice:50051"
  CURRENCY_SERVICE_URL: "http://currencyservice:7000"

  # =========================
  # REDIS
  # =========================
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
