apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-deployment
  labels:
    app: checkout-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-service
  template:
    metadata:
      labels:
        app: checkout-service
    spec:
      containers:
      - name: checkout-container
        image: docker.io/yugandhar7/checkout-svc:v2
        ports:
        - containerPort: 5050
        env:
        - name: PORT
          value: "5050"

        - name: CART_SERVICE_ADDR
          value: "cart-service:7070"

        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "product-catalog-service:3550"

        - name: PAYMENT_SERVICE_ADDR
          value: "payment-service:50051"

        - name: SHIPPING_SERVICE_ADDR
          value: "shipping-service:50051"

        - name: EMAIL_SERVICE_ADDR
          value: "email-service:8080"

        - name: CURRENCY_SERVICE_ADDR
          value: "currency-service:7000"