apiVersion: v1
kind: Service
metadata:
  name: checkout-service
  labels:
    app: checkout-service
spec:
  type: ClusterIP
  selector:
    app: checkout-service
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050