apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/yugandhar7/frontend:v2

        ports:
        - containerPort: 8080

        # ✅ REQUIRED runtime env vars (Go binary)
        env:
        - name: PORT
          value: "8080"

        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "product-catalog-service:3550"

        - name: CART_SERVICE_ADDR
          value: "cart-service:7070"

        - name: CURRENCY_SERVICE_ADDR
          value: "currency-service:7000"

        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendation-service:8080"

        - name: AD_SERVICE_ADDR
          value: "ad-service:9555"

        - name: EMAIL_SERVICE_ADDR
          value: "email-service:8080"

        - name: PAYMENT_SERVICE_ADDR
          value: "payment-service:50051"

        - name: SHIPPING_SERVICE_ADDR
          value: "shipping-service:50051"
        - name: CHECKOUT_SERVICE_ADDR
          value: "checkout-service:5050"
        - name: SHOPPING_ASSISTANT_SERVICE_ADDR
          value: "shopping-assistant-service:5050"







        # ✅ Optional: browser config (still useful)
        envFrom:
        - configMapRef:
            name: frontend-config

        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30

        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
